services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana-data:/var/lib/grafana
      - /etc/localtime:/etc/localtime:ro
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    restart: unless-stopped

  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    ports:
      - "8086:8086"         # InfluxDB HTTP API
      # - "8083:8083"      # (選) InfluxDB v1 Web介面 (大多已不建議使用)
    environment:
      - TZ=Asia/Taipei        # 時區，依你的需要可調整
      - INFLUXDB_DB=jmeter      # 啟動時預設建立的 database
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
#      - INFLUXDB_USER=myuser
#      - INFLUXDB_USER_PASSWORD=mypw
    volumes:
      - ./influxdb-data:/var/lib/influxdb
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
