global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Prometheus 自身監控
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # 監控 Linux 主機 (node_exporter)
  - job_name: 'linux-node'
    static_configs:
      - targets: ['node_exporter:9100']
        labels:
          instance: 'ubuntu-server'

  # 監控 Windows 主機 (windows_exporter)
  # 需要在 Windows 主機安裝 windows_exporter
  # 下載：https://github.com/prometheus-community/windows_exporter/releases
  - job_name: 'windows-node'
    static_configs:
      - targets: []  # 填入 Windows 主機 IP:9182，例如 ['192.168.1.100:9182']
        labels:
          instance: 'windows-server'
